server:
  port: 8989
  servlet:
    context-path: /api

spring:
  application:
    name: bugs-and-bytes
  datasource:
    url: jdbc:mysql://localhost:3306/criative_experience_db?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.hibernate: DEBUG
  file:
    name: application.log
