server:
  port: 8080
  servlet:
    context-path: /booknow

spring:
  application:
    name: book-now
  banner:
    location: classpath:banner.txt
    charset: UTF-8
  datasource:
    url: jdbc:mysql://localhost:3306/booknow?serverTimezone=UTC&useSSL=false
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: false
  jackson:
    date-format: "dd/MM/yyyy HH:mm:ss"
    locale: 'pt-BR'
    time-zone: 'America/Sao_Paulo'
    default-property-inclusion: NON_NULL
  messages:
    basename: messages
    fallback-to-system-locale: false
    encoding: UTF-8
  mvc:
    locale:
      default-locale: pt
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'petshop.petconnect@gmail.com'
    password: 'zrgh nfow yzlb eext'
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          from: 'petshop.petconnect@gmail.com'
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100
        one-indexed-parameters: false
        default-page-number: 0
        sort:
          sort-parameter: sort

security:
  jwt:
    secret-key: '05955a2232d7f31a0a9879c9233e661f6e2923d5334ec67b7a64c79911407afc'
    expiration-time: 86400000

logging:
  file:
    name: booknow.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n'
  level:
    web: DEBUG
    org.springframework.boot: DEBUG
    br.com.finalproject.petconnect: INFO