server:
  port: 8888
  servlet:
    context-path: /api/hotel

spring:
  application:
    name: book-now
  devtools:
    add-properties: true # habilitado
  datasource:
    url: jdbc:mysql://localhost:3306/book_now_db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    web: DEBUG